// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import EditTitleController from "./edit_title_controller"
application.register("edit-title", EditTitleController)

import FavouriteAddressController from "./favourite_address_controller"
application.register("favourite-address", FavouriteAddressController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InspirationController from "./inspiration_controller"
application.register("inspiration", InspirationController)

import MapController from "./map_controller"
application.register("map", MapController)

import MoodController from "./mood_controller"
application.register("mood", MoodController)

import TagtoggleController from "./tagtoggle_controller"
application.register("tagtoggle", TagtoggleController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)
